name: CI

on: [push, workflow_dispatch]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "outfile=`make outfile`" >> $GITHUB_ENV
      - run: ln -s $PWD/minecraft-fonts /usr/share/fonts/minecraft
      - run: make -j$(nproc) all
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.outfile }}
          path: ${{ env.outfile }}
